repos:
  - repo: local
    hooks:
      - id: lint
        name: lint
        entry: env PYTHONPATH="." python -m pylint basicfs/
        language: system
        always_run: true
        pass_filenames: false