version: 2.1

jobs:
    build:
        machine: true
        steps:
            - checkout

            # build and run docker image
            - run: |
                ./docker.sh
            - run: |
                ./test.py

